In [35]:
import tensorflow as tf

In [36]:
tf.__version__

'1.14.0'

In [5]:
hello_constant = tf.constant("Hello World")
hello_constant

<tf.Tensor 'Const:0' shape=() dtype=string>

In [6]:
hello_constant = tf.constant("Hello World")

with tf.Session() as sess:
    output = sess.run(hello_constant)
    print(output)

b'Hello World'


In [7]:
A = tf.constant(1234) # 0 dimensional 

B = tf.constant([123,456,789]) # 1 dimensional

C = tf.constant([[123,456,789],[222,333,444]]) # 2 dimensional

In [8]:
with tf.Session() as sess:
    output = sess.run(C)
    print(output)

[[123 456 789]
 [222 333 444]]


In [10]:
x = tf.placeholder(tf.string)

with tf.Session() as sess:
    output = sess.run(x, feed_dict={x: 'Hello World'})
    print(output)

Hello World


In [12]:
x = tf.placeholder(tf.int64)

with tf.Session() as sess:
    output = sess.run(x, feed_dict={x: 123456})
    print(output)

123456


In [20]:
a = tf.placeholder(tf.string)
b = tf.placeholder(tf.int64)
c = tf.placeholder(tf.float64)
l = [a,b,c]
with tf.Session() as sess:
    for i in l:
        output_i = sess.run(i,feed_dict={a:"Fazlullah", b:123, c:45.25})
        print(output_i)
    #output_x = sess.run(a,feed_dict={a:"Fazlullah", b:123, c:45.25})
    #output_y = sess.run(b,feed_dict={a:"Fazlullah", b:123, c:45.25})
    #output_z = sess.run(c,feed_dict={a:"Fazlullah", b:123, c:45.25})
    #print(output_x)
    #print(output_y)
    #print(output_z)

Fazlullah
123
45.25


In [27]:
x = tf.add(5,2)
with tf.Session() as sess:
    output_x = sess.run(x)
    print(output_x)

7


In [28]:
y = tf.multiply(4,5)

with tf.Session() as sess:
    output = sess.run(y)
    print(output)

20


In [29]:
2.0-1

1.0

In [30]:
tf.subtract(6,7.0)

TypeError: Expected int32 passed to parameter 'y' of op 'Sub', got 7.0 of type 'float' instead. Error: Expected int32, got 7.0 of type 'float' instead.

In [40]:
tf.subtract(tf.cast(tf.constant(4.0),tf.int32),tf.constant(2))

<tf.Tensor 'Sub_6:0' shape=() dtype=int32>

In [37]:
a = tf.subtract(4,2)

with tf.Session() as sess:
    result = sess.run(a)
    print(result)

2


In [42]:
x = tf.constant(10)
y = tf.constant(2)
z = tf.subtract(tf.divide(x,y),1)

with tf.Session() as sess:
    result = sess.run(z)
    print(result)

4.0


In [45]:
x = tf.Variable(5)
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    sess.run(x)

In [48]:
n_feature = 120
n_label = 5
weight = tf.Variable(tf.truncated_normal((n_feature,n_label)))

In [51]:
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    o = sess.run(tf.truncated_normal((n_feature,n_label)))
    print(o)

[[-1.78229046e+00  7.12373316e-01  9.50152203e-02  7.72950530e-01
   1.42679811e+00]
 [-1.69060993e+00 -1.07432187e+00  1.31375387e-01  1.55565882e+00
  -8.38330626e-01]
 [-1.38872671e+00  1.00698388e+00  6.36212081e-02 -8.23399484e-01
   1.23199493e-01]
 [-1.68869233e+00 -5.01301944e-01 -4.76493835e-01  7.72438705e-01
  -9.06099021e-01]
 [-9.77450132e-01 -1.68816626e+00 -6.12826645e-02  1.17692135e-01
   8.32875192e-01]
 [ 4.78412896e-01 -1.28392208e+00  3.28687072e-01  4.31022644e-01
   3.57631415e-01]
 [-1.92399651e-01  2.58629955e-02  8.87870669e-01  1.85272828e-01
   6.92378581e-02]
 [ 5.63624263e-01  2.36344576e-01 -4.29307260e-02 -1.03830588e+00
   7.69200027e-01]
 [ 1.79546848e-01 -1.28406942e+00  1.71832228e+00 -6.11271486e-02
   5.54938376e-01]
 [ 1.58209288e+00 -5.88896453e-01 -5.11873960e-01 -4.13597465e-01
  -1.16800451e+00]
 [ 6.55374229e-01 -3.93907763e-02  2.98953444e-01  3.07605207e-01
  -4.11301970e-01]
 [-6.55502751e-02  1.74232399e+00  1.03857160e+00  9.17126954e-01

In [58]:
import numpy as np
np.zeros([5,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [63]:
n_label = 5
bias = tf.Variable(tf.zeros(n_label))

In [65]:
x = tf.nn.softmax([2.0,1.0,0.2])

with tf.Session() as sess:
    o = sess.run(x)
    print(o)

[0.65223986 0.23994564 0.10781453]


In [66]:
def run_2():
    output = None
    logit_data = [2.0,1.0,0.1]
    logits = tf.placeholder(tf.float32)
    
    softmax = tf.nn.softmax(logit_data)
    
    with tf.Session() as sess:
        output = sess.run(softmax, feed_dict={logits:logit_data})
        
    return output

print(run_2())

[0.6590012  0.24243298 0.09856589]


In [67]:
x = tf.reduce_sum([1,2,3,4,5])

with tf.Session() as sess:
    o = sess.run(x)
    print(o)

15


In [68]:
l = tf.log(100.0)

with tf.Session() as sess:
    o = sess.run(l)
    print(o)

4.6051702


In [69]:
softmax_data = [0.7,0.2,0.1]
one_hot_data = [1.0,0.0,0.0]

softmax = tf.placeholder(tf.float32)
one_hot = tf.placeholder(tf.float32)

cross_entropy = -tf.reduce_sum(tf.multiply(one_hot_data,tf.log(softmax_data)))

with tf.Session() as sess:
    result = sess.run(cross_entropy, feed_dict={one_hot:one_hot_data, softmax:softmax_data})
    print(result)

0.35667497
